### ISSUE TITLE
Error: No valid gas coins found for the transaction when trigger deposit() or depositCollateral()

### ISSUE THREAD

**Issue by binhnguyen2501** [scallop-io/sui-scallop-sdk#127]
@nicetomeetyou1  i got error Error: No valid gas coins found for the transaction when i trigger  deposit() or depositCollateral(). Could you please take a look this issue
<img width="506" alt="Screenshot 2024-06-25 at 17 47 27" src="https://github.com/scallop-io/sui-scallop-sdk/assets/72795100/eb203b26-be2a-433d-8c68-593714e1ca6f">

**Comment by nicetomeetyou1** [comment]
@binhnguyen2501 Could you elaborate on the details? For example, please provide your code and specify which network you use to interact with the Scallop SDK. Is it mainnet or testnet?

**Comment by binhnguyen2501** [comment]
i use sui mainnet with rpcUrl: "https://fullnode.mainnet.sui.io" when interact with the Scallop SDK @nicetomeetyou1

**Comment by binhnguyen2501** [comment]
i use mainnet when interact with the Scallop SDK @nicetomeetyou1 
<img width="330" alt="image" src="https://github.com/scallop-io/sui-scallop-sdk/assets/72795100/2aa9f9c8-cf0e-40ee-9b64-d5f17823a84b">

**Comment by fum-is-chum** [comment]
Hi @binhnguyen2501 can you provide the wallet address that is trying to call this function? I've just tested both `deposit` and `depositCollateral`, they work just fine

**Comment by binhnguyen2501** [comment]
here is my sui wallet address: 0x389878a582bc9c322ece92f55f269660d1996d3f5111ed41738561cbe71aa8ec and the code i interact with the Scallop SDK
<img width="508" alt="image" src="https://github.com/scallop-io/sui-scallop-sdk/assets/72795100/95e2d7ee-3544-4615-93ab-368bce220ff5">
@fum-is-chum

**Comment by fum-is-chum** [comment]
Are you using the latest sdk version `v0.46.39`?

**Comment by nicetomeetyou1** [comment]
@binhnguyen2501 I think there’s a missing parameter value that you need to pass to ScallopClient. You need to provide the address that will sign the transaction.

```ts
import { Scallop, ScallopClient } from "@scallop-io/sui-scallop-sdk";
import dotenv from "dotenv";
dotenv.config();

async function  main() {
  const scallop = new Scallop({
    mnemonics: process.env.MNEMONICS,
  });
  const yourWalletAddress = scallop.suiKit.accountManager.currentAddress; // You can get the address from `@mysten/dapp-kit` to get the address from frontend.
  const scallopClient = new ScallopClient({
    walletAddress: yourWalletAddress,
    networkType: 'mainnet'
  })
  await scallopClient.init();
  const client = await scallop.createScallopClient();
  const { digest } = await client.depositCollateral('sui', 1e9);
  console.log(digest);
}

main().catch(console.error);
```

**Comment by fum-is-chum** [comment]
It seems like the only possible way to reproduce this bug is when the wallet that is used to sign the tx is different from this one `0x389878a582bc9c322ece92f55f269660d1996d3f5111ed41738561cbe71aa8ec`
Can you share a bit more of the real code that you're working with? We can help you spot the misconfiguration or mistake @binhnguyen2501

**Comment by binhnguyen2501** [comment]
base on https://github.com/scallop-io/sui-scallop-sdk maybe I missed adding the wallet address to your Scallop Client SDK unit. I will try again and send you a reply as soon as possible @nicetomeetyou1 @fum-is-chum

**Comment by binhnguyen2501** [comment]
> Are you using the latest sdk version `v0.46.39`? @binhnguyen2501

yes i use the lastest sdk version

**Comment by fum-is-chum** [comment]
> Updated my code base on @nicetomeetyou1 but i still got the same issue
> 
> <img alt="image" width="506" src="https://private-user-images.githubusercontent.com/72795100/343045987-ee7bb62e-b598-4e6a-8073-ba2ec9902199.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODY0ODksIm5iZiI6MTcxOTM4NjE4OSwicGF0aCI6Ii83Mjc5NTEwMC8zNDMwNDU5ODctZWU3YmI2MmUtYjU5OC00ZTZhLTgwNzMtYmEyZWM5OTAyMTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA3MTYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZDFmZTMwYmVkZDFkM2I0ZWU3ZjkyZDc1NzAyYzlhMjFmYTMzYTA5ZWEwYzUzZWUxODQ1MTNmYjExMTA1NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iXBcQunjMG2yYXcZ6FYbazU65jLzTieE20vh_V9uDj4"> <img alt="image" width="566" src="https://private-user-images.githubusercontent.com/72795100/343045596-43d66efd-d6ae-46cb-9538-1d09b12fa9ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODY0ODksIm5iZiI6MTcxOTM4NjE4OSwicGF0aCI6Ii83Mjc5NTEwMC8zNDMwNDU1OTYtNDNkNjZlZmQtZDZhZS00NmNiLTk1MzgtMWQwOWIxMmZhOWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA3MTYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiOWViNGJkMmVhMjUyMGMzZjE1Mzg2OTEyZTE4MDY5MDBjNTcwNjE1Mjg3ZWQ3YWVhOGU1YjEwOTBiMWY5NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uHUSIGldhOLCIaz2nhx5cWNDlzjx80g5VwigddxKp6s">

It seems like there's another instance `scallopClient`? Shouldn't it be `scallopClientSDK.deposit`?

**Comment by binhnguyen2501** [comment]
> > Updated my code base on @nicetomeetyou1 but i still got the same issue
> > <img alt="image" width="506" src="https://private-user-images.githubusercontent.com/72795100/343045987-ee7bb62e-b598-4e6a-8073-ba2ec9902199.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODY0ODksIm5iZiI6MTcxOTM4NjE4OSwicGF0aCI6Ii83Mjc5NTEwMC8zNDMwNDU5ODctZWU3YmI2MmUtYjU5OC00ZTZhLTgwNzMtYmEyZWM5OTAyMTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA3MTYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZDFmZTMwYmVkZDFkM2I0ZWU3ZjkyZDc1NzAyYzlhMjFmYTMzYTA5ZWEwYzUzZWUxODQ1MTNmYjExMTA1NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iXBcQunjMG2yYXcZ6FYbazU65jLzTieE20vh_V9uDj4"> <img alt="image" width="566" src="https://private-user-images.githubusercontent.com/72795100/343045596-43d66efd-d6ae-46cb-9538-1d09b12fa9ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODY0ODksIm5iZiI6MTcxOTM4NjE4OSwicGF0aCI6Ii83Mjc5NTEwMC8zNDMwNDU1OTYtNDNkNjZlZmQtZDZhZS00NmNiLTk1MzgtMWQwOWIxMmZhOWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA3MTYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiOWViNGJkMmVhMjUyMGMzZjE1Mzg2OTEyZTE4MDY5MDBjNTcwNjE1Mjg3ZWQ3YWVhOGU1YjEwOTBiMWY5NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uHUSIGldhOLCIaz2nhx5cWNDlzjx80g5VwigddxKp6s">
> 
> It seems like there's another instance `scallopClient`? Shouldn't it be `scallopClientSDK.deposit`?

After updated my code base on @nicetomeetyou1  i still got the above issue 

<img width="506" alt="image" src="https://github.com/scallop-io/sui-scallop-sdk/assets/72795100/6bb3d091-c102-446e-b3da-f1e88660d65c">

<img width="506" alt="image" src="https://github.com/scallop-io/sui-scallop-sdk/assets/72795100/196b7920-66b6-49be-9d2b-e2be430b4479">

**Comment by nicetomeetyou1** [comment]
@binhnguyen2501  try like this one

```ts
import { Scallop, ScallopBuilder, ScallopClient, ScallopQuery } from "@scallop-io/sui-scallop-sdk";
import { SuiKit } from '@scallop-io/sui-kit';
import dotenv from "dotenv";
dotenv.config();

async function  main() {
  const suiKit = new SuiKit({
    mnemonics: process.env.MNEMONICS,
    networkType: 'mainnet',
  })
  const scallopClient = new ScallopClient({
    networkType: 'mainnet',
  });
  const scallopQuery = new ScallopQuery({
    networkType: 'mainnet',
  })
  const scallopBuilder = new ScallopBuilder({
    networkType: 'mainnet',
    walletAddress: suiKit.currentAddress(),
  });
  await scallopBuilder.init();
  await scallopQuery.init();
  await scallopClient.init();

  const obligationAddress = await scallopQuery.getObligations(suiKit.currentAddress());

  // if no obligation found, plese create one first;
  let obligationId = undefined
  if(obligationAddress.length === 0) {
    obligationId = obligationAddress[0].id;
  } 
  const txBlock = await scallopClient.depositCollateral('sui', 1e9, false, obligationId, suiKit.currentAddress());
  const { digest } = await suiKit.signAndSendTxn(txBlock); // You can use signAndExecuteTransactionBlock() from `@mysten/dapp-kit` for frontend.
  console.log('digest', digest);
}

main().catch(console.error);
```

In the frontend, you will use @mysten/dapp-kit, right? The error occurs because the transaction is executed by the sukit package, but on the frontend, you don’t use this package. Therefore, you need to pass the `false` value to function `depositCollateral`. This way, you will receive a TransactionBlock as a return from the depositCollateral function. Once you get the return from the function, you can sign and execute the transaction.

**Comment by binhnguyen2501** [comment]
> @binhnguyen2501 try like this one
> 
> ```ts
> import { Scallop, ScallopBuilder, ScallopClient, ScallopQuery } from "@scallop-io/sui-scallop-sdk";
> import { SuiKit } from '@scallop-io/sui-kit';
> import dotenv from "dotenv";
> dotenv.config();
> 
> async function  main() {
>   const suiKit = new SuiKit({
>     mnemonics: process.env.MNEMONICS,
>     networkType: 'mainnet',
>   })
>   const scallopClient = new ScallopClient({
>     networkType: 'mainnet',
>   });
>   const scallopQuery = new ScallopQuery({
>     networkType: 'mainnet',
>   })
>   const scallopBuilder = new ScallopBuilder({
>     networkType: 'mainnet',
>     walletAddress: suiKit.currentAddress(),
>   });
>   await scallopBuilder.init();
>   await scallopQuery.init();
>   await scallopClient.init();
> 
>   const obligationAddress = await scallopQuery.getObligations(suiKit.currentAddress());
> 
>   let obligationId = undefined
>   if(obligationAddress.length === 0) {
>     obligationId = obligationAddress[0].id;
>   } 
>   const txBlock = await scallopClient.depositCollateral('sui', 1e9, false, obligationId, suiKit.currentAddress());
>   const { digest } = await suiKit.signAndSendTxn(txBlock); // You can use signAndExecuteTransactionBlock() from `@mysten/dapp-kit` for frontend.
>   console.log('digest', digest);
> }
> 
> main().catch(console.error);
> ```
> 
> In the frontend, you will use @mysten/dapp-kit, right? The error occurs because the transaction is executed by the sukit package, but on the frontend, you don’t use this package. Therefore, you need to pass the `false` value to function `depositCollateral`. This way, you will receive a TransactionBlock as a return from the depositCollateral function. Once you get the return from the function, you can sign and execute the transaction.
> 
> The `depositCollateral` function will create a new obligation account if the address does not already have one.

I think there were some mistakes when checking the if(obligationAddress.length === 0) condition (the condition should obligationAddress.length !== 0) however everything worked perfectly, thank you so much for your support @nicetomeetyou1  @fum-is-chum @mr-donor . Your team work so hard and great <3

**Comment by binhnguyen2501** [comment]
when I call the scallopClient.withdraw() function with an amount of 1.900021557201201, your sdk returns an invalid error and forces rounding, while using the production side it does not and i can withdraw all my asset. Hope you can help me with this issue @nicetomeetyou1  @fum-is-chum 
![image](https://github.com/scallop-io/sui-scallop-sdk/assets/72795100/5975298d-0ba9-4bdd-914d-3b0042006b95)

<img width="511" alt="image" src="https://github.com/scallop-io/sui-scallop-sdk/assets/72795100/2dfc829f-6466-49f4-92f6-9a2b7510d74c">

**Comment by binhnguyen2501** [comment]
If during the processing process the RPC fails, will our SDK automatically retry sir @nicetomeetyou1  @fum-is-chum

**Comment by nicetomeetyou1** [comment]
@binhnguyen2501 There's no auto retry when there's a problem with RPC.
