### ISSUE TITLE
Errors after importing @scallop-io/sui-scallop-sdk

### ISSUE THREAD

**Issue by ernest-zulpukarov** [scallop-io/sui-scallop-sdk#145]
Hello,

I'm encountering errors after importing the `@scallop-io/sui-scallop-sdk` package into my project.

**Import statement:**
```typescript
import { SupportPoolCoins } from '@scallop-io/sui-scallop-sdk';
```

**Error Output:**
```shell
>>> tsc

Found 10 errors in 3 files.

Errors  Files
     1  node_modules/@scallop-io/sui-kit/node_modules/@mysten/sui.js/src/client/rpc-websocket-client.ts:157
     2  node_modules/@scallop-io/sui-kit/node_modules/@mysten/sui.js/src/transactions/TransactionBlock.ts:831
     7  node_modules/@scallop-io/sui-kit/node_modules/@mysten/sui.js/src/transactions/TransactionBlockData.ts:78
```

Neither `skipLibCheck` nor `exclude` options in `tsconfig.json` resolve the issue.

Currently, I have temporarily fixed it using:
```typescript
const scallop = require('@scallop-io/sui-scallop-sdk');
```
However, I still need TypeScript typings.

Any help would be appreciated!

Thank you.

**Comment by nicetomeetyou1** [comment]
Hello @hokage229, Have you already installed `@mysten/sui.js` in your project? and Which version are you currently using?

**Comment by hokage229** [comment]
No, I use instead `@mysten/sui` in my project. And `@mysten/sui.js@0.52.0` installed in node modules as dependency of `@scallop-io/sui-scallop-sdk`

**Comment by nicetomeetyou1** [comment]
I tried updating my tsconfig with `target: "ESNext"`, and it works fine when running the build.
