### ISSUE TITLE
Missing getRewardPool function implementation

### ISSUE THREAD

**Issue by suspended** [scallop-io/sui-scallop-sdk#56]
In multiple places in the documentation, a function such as const `rewardPool = await scallopQuery.getRewardPool('ssui');` is shown but the SDK does not implement `getRewardPool(s)`. Is this a bug?

**Comment by mr-donor** [comment]
This is a writing error in the documentation, the correct function names should be `getStakeRewardPool` and `getStakeRewardPools`.

It would be fixed by this repo: https://github.com/scallop-io/sui-scallop-sdk/pull/59
